# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_lltm_sgd <- function(params, lr, momentum, dampening, weight_decay, nesterov) {
    .Call('_lltm_rcpp_lltm_sgd', PACKAGE = 'lltm', params, lr, momentum, dampening, weight_decay, nesterov)
}

rcpp_lltm_sgd_step <- function(opt) {
    invisible(.Call('_lltm_rcpp_lltm_sgd_step', PACKAGE = 'lltm', opt))
}

rcpp_lltm_sgd_zero_grad <- function(opt) {
    invisible(.Call('_lltm_rcpp_lltm_sgd_zero_grad', PACKAGE = 'lltm', opt))
}

rcpp_lltm_run_script_module <- function(network, loss_fn, input, target) {
    .Call('_lltm_rcpp_lltm_run_script_module', PACKAGE = 'lltm', network, loss_fn, input, target)
}

rcpp_lltm_forward <- function(input, weights, bias, old_h, old_cell) {
    .Call('_lltm_rcpp_lltm_forward', PACKAGE = 'lltm', input, weights, bias, old_h, old_cell)
}

rcpp_lltm_backward <- function(grad_h, grad_cell, new_cell, input_gate, output_gate, candidate_cell, X, gate_weights, weights) {
    .Call('_lltm_rcpp_lltm_backward', PACKAGE = 'lltm', grad_h, grad_cell, new_cell, input_gate, output_gate, candidate_cell, X, gate_weights, weights)
}

rcpp_delete_optim_sgd <- function(x) {
    invisible(.Call('_lltm_rcpp_delete_optim_sgd', PACKAGE = 'lltm', x))
}

rcpp_delete_graph_function <- function(x) {
    invisible(.Call('_lltm_rcpp_delete_graph_function', PACKAGE = 'lltm', x))
}

rcpp_delete_stack2 <- function(x) {
    invisible(.Call('_lltm_rcpp_delete_stack2', PACKAGE = 'lltm', x))
}

lltm_raise_exception <- function() {
    invisible(.Call('_lltm_lltm_raise_exception', PACKAGE = 'lltm'))
}

